### ISSUE TITLE
bug: index prefix for operate/ tasklist ignored

### ISSUE THREAD

**Issue by hisImminence** [camunda/issues#920]
**Describe the bug**

related to [SUPPORT-25039](https://jira.camunda.com/browse/SUPPORT-25039?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D)

There was a previous incident [#inc-support-25039-upgrade-self-managed-cluster-failed ](https://jira.camunda.com/browse/SUPPORT-25039#)and github issue [#2709](https://github.com/camunda/camunda-platform-helm/issues/2709). This was specific to Optimize. Customer had configured some env variable which was ignored by the migration and later lead to the upgrade failing as the schema hadn’t been upgraded.

The fix is working but they are now seeing the same issue for Operate.

We need togeneralise the previous fix across other applications such as Operate and Tasklist.

**To Reproduce**

Best guess (not yet reproduced):
Upgrade a cluster from 8.5 to 8.6 and set prefix-indicies envVars for Operate and Tasklist. These are ignored.

This was the used fix in the support case [`CAMUNDA_OPERATE_ELASTICSEARCH_INDEXPREFIX`]:

```
operate:   env:     - name: CAMUNDA_OPERATE_ELASTICSEARCH_INDEXPREFIX
      value: operate-{{ .Environment.Name }}
    - name: CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_PREFIX
      value: zeebe-record-{{ .Environment.Name }}
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_NUMBEROFSHARDS
      value: "1"
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_NUMBEROFREPLICAS
      value: "1"
    - name: CAMUNDA_OPERATE_BACKUP_REPOSITORY_NAME
      value: {{ .Release.Name | quote }}
  migration:     env:       - name: CAMUNDA_OPERATE_ELASTICSEARCH_INDEXPREFIX
        value: operate-{{ .Environment.Name }}
      - name: CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_PREFIX
        value: zeebe-record-{{ .Environment.Name }}
      - name: CAMUNDA_OPERATE_ELASTICSEARCH_NUMBEROFSHARDS
        value: "1"
      - name: CAMUNDA_OPERATE_ELASTICSEARCH_NUMBEROFREPLICAS
        value: "1"
```

**Expected behavior**

Prefixed indices are in Operate and Tasklist are taken into account on migration.

### Tasks

* [ ] We have a documentation about setting ES prefixes for HC and EnvVars based on: https://github.com/camunda/issues/issues/920#issuecomment-2733060572.

**Environment:**
- OS: 
- Zeebe Version: 
- Configuration:

**Comment by hisImminence** [comment]
We should fix it for 8.7

**Comment by hisImminence** [comment]
@drodriguez-305 - as you did the fix for optimize. Could you implement the fix for operate and tasklist as well?

**Comment by hisImminence** [comment]
We are not sure if this is supported in Operate and Tasklist actually as we dont find EnvVars documented in the documentation.

**Comment by hisImminence** [comment]
Asking the [operate team](https://camunda.slack.com/archives/C9B5270DA/p1739998355184969) if supported and what would be the envVar!

thanks @drodriguez-305 for the catch!

**Comment by hisImminence** [comment]
We got the following shared
```
global:
  elasticsearch:
    prefix: custom-zeebe
operate:
  env: 
  - name: CAMUNDA_OPERATE_ELASTICSEARCH_INDEXPREFIX
    value: custom-operate
  migration:
    env:
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_INDEXPREFIX
      value: custom-operate
tasklist:
  env: 
  - name: CAMUNDA_TASKLIST_ELASTICSEARCH_INDEXPREFIX
    value: custom-tasklist
optimize:
  env:
  - name: CAMUNDA_OPTIMIZE_ELASTICSEARCH_SETTINGS_INDEX_PREFIX
    value: custom-optimize
  - name: CAMUNDA_OPTIMIZE_ZEEBE_NAME
    value: custom-zeebe
  migration:
    env:
    - name: CAMUNDA_OPTIMIZE_ELASTICSEARCH_SETTINGS_INDEX_PREFIX
      value: custom-optimize
```

**Comment by hisImminence** [comment]
Related to: https://github.com/camunda/camunda-platform-helm/issues/1859

**Comment by hisImminence** [comment]
From the slack message. This is how I understood it should work:

When setting

```
global:
  elasticsearch:
    prefix: custom-zeebe
```

--> zeebe is exporting its indices with the custom-zeeb prefix. This is being applied to all apps for importing, but Optimize - Optimize needs this information on top, thats why we need to set:
```
optimize:
  env:
  - name: CAMUNDA_OPTIMIZE_ZEEBE_NAME
    value: custom-zeebe
```


All the other custom prefixes is set to export also custom indices. All of them but tasklist need to also set this custom-indice for migration. Tasklist does not need it as it does not have a migration path:
```
operate:
  env: 
  - name: CAMUNDA_OPERATE_ELASTICSEARCH_INDEXPREFIX
    value: custom-operate
  migration:
    env:
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_INDEXPREFIX
      value: custom-operate
tasklist:
  env: 
  - name: CAMUNDA_TASKLIST_ELASTICSEARCH_INDEXPREFIX
    value: custom-tasklist
optimize:
  env:
  - name: CAMUNDA_OPTIMIZE_ELASTICSEARCH_SETTINGS_INDEX_PREFIX
    value: custom-optimize
  migration:
    env:
    - name: CAMUNDA_OPTIMIZE_ELASTICSEARCH_SETTINGS_INDEX_PREFIX
      value: custom-optimize
```

Follow up questions/ actions:
* Test this setup and make sure its working
   * make a unit test for it 
* What is the migration path for the other apps so that tasklist does not need to set the envVar?
   * --> Tasklist does not have an init container. It does not export indicies but only read. 
* The customer reported that the custom indices are not taken into account by operate during migration. Reproduce this (11.01 to 11.1.0)!

**Comment by hisImminence** [comment]
The issue might be that this configuration can not be set on the fly. 
We are not sure if this is then only a feature for new installation. If it supported in migration/ changing on the fly - it might be a feature request.

@hisImminence to understand this issue better and then check if its a FR or a bug.

**Comment by aabouzaid** [comment]
@hisImminence, are there any updates about this issue, please?

**Comment by hisImminence** [comment]
> [@hisImminence](https://github.com/hisImminence), are there any updates about this issue, please?

Thanks for the ping. I confirmed the configuration but could not yet reproduce the error in operate. 

The fix is regarding the support ticket to set the following for operate:
```
operate:   env:     - name: CAMUNDA_OPERATE_ELASTICSEARCH_INDEXPREFIX
      value: operate-{{ .Environment.Name }}
    - name: CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_PREFIX
      value: zeebe-record-{{ .Environment.Name }}
  migration:     env:       - name: CAMUNDA_OPERATE_ELASTICSEARCH_INDEXPREFIX
        value: operate-{{ .Environment.Name }}
      - name: CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_PREFIX
        value: zeebe-record-{{ .Environment.Name }}
```

**Comment by hisImminence** [comment]
Will move it to ready as all information should be there!

**Comment by hisImminence** [comment]
As reported by the customer, the envVar: `CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_PREFIX ` is missing in Operate ( operate deployment and init container).

This is also documented in the docs for:
* [Operate](https://docs.camunda.io/docs/self-managed/operate-deployment/operate-configuration/#example-of-applicationyml-file)
* [Tasklist](https://docs.camunda.io/docs/self-managed/tasklist-deployment/tasklist-configuration/#zeebe-elasticsearch-or-opensearch-exporter)

I was testing this with 11.2.2:

<img width="603" alt="Image" src="https://github.com/user-attachments/assets/acf0da83-1868-4896-aca9-0db9c8cc6605" />

**Comment by hisImminence** [comment]
The final setup therefore needs to be: 

```
## HC values.yaml

elasticsearch:
  prefix: custom-zeebe

operate:
  env: 
  - name: CAMUNDA_OPERATE_ELASTICSEARCH_INDEXPREFIX
    value: custom-operate
  - name: CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_PREFIX
    value: custom-zeebe
  migration:
    env:
    - name: CAMUNDA_OPERATE_ELASTICSEARCH_INDEXPREFIX
      value: custom-operate
    - name: CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_PREFIX
      value: custom-zeebe

optimize:
  env:
  - name: CAMUNDA_OPTIMIZE_ELASTICSEARCH_SETTINGS_INDEX_PREFIX
    value: custom-optimize
  migration:
    env:
    - name: CAMUNDA_OPTIMIZE_ELASTICSEARCH_SETTINGS_INDEX_PREFIX
      value: custom-optimize
    - name: CAMUNDA_OPTIMIZE_ZEEBE_NAME
      value: custom-zeebe

tasklist:
  env: 
  - name: CAMUNDA_TASKLIST_ELASTICSEARCH_INDEXPREFIX
    value: custom-tasklist
   - name: CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_PREFIX
      value: custom-zeebe
```

I updated the ticket to provide a guide in the SM section about it (operational guide).
